export enum LicenseType {
    LICENCIA_MEDICA = 'LICENCIA_MEDICA',
    LICENCIA_POR_RAZONES_FAMILIARES = 'LICENCIA_POR_RAZONES_FAMILIARES',
    LICENCIA_POR_MATRIMONIO = 'LICENCIA_POR_MATRIMONIO',
    LICENCIA_POR_ESTUDIO = 'LICENCIA_POR_ESTUDIO',
    LICENCIA_POR_VACACIONES = 'LICENCIA_POR_VACACIONES',
    LICENCIA_ESPECIAL = 'LICENCIA_ESPECIAL'
}